#!/bin/bash

for k in 1000 100000; do
for i in $(seq -w 10); do
    echo "instance $i with k=$k"
    echo "Built-in implementation"
    (
        ulimit -t 60
        ulimit -v 2000000
        ./fast-downward/fast-downward.py nomystery-opt11-strips/p$i.pddl --search "astar(ipdb(collection_max_size=$k, min_improvement=1))" | grep "Expanded until last jump\|Total time\|Search time"
    )
    echo "PlanOpt implementation"
    (
        ulimit -t 60
        ulimit -v 2000000
        ./fast-downward/fast-downward.py nomystery-opt11-strips/p$i.pddl --search "astar(planopt_ipdb(size_bound=$k))" | grep "Expanded until last jump\|Total time\|Search time"
    )
    echo
done
done
